import { StyleSheet } from "react-native";
import { COLORS } from "../../../constants/theme";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#ecfdf5" },
  scrollView: { flex: 1 },

  // Header
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingTop: 48,
    paddingBottom: 20,
    paddingHorizontal: 20,
  },
  backButton: {
    padding: 8,
    backgroundColor: "rgba(255,255,255,0.2)",
    borderRadius: 12,
  },
  headerTitle: {
    flex: 1,
    textAlign: "center",
    fontSize: 20,
    fontWeight: "700",
    color: COLORS.WHITE,
  },
  headerSpacer: { width: 40 },
  historyButton: {
    padding: 8,
    backgroundColor: "rgba(255,255,255,0.2)",
    borderRadius: 12,
  },

  // Content
  content: { padding: 20 },

  // Hero
  heroCard: {
    backgroundColor: COLORS.WHITE,
    borderRadius: 20,
    padding: 24,
    alignItems: "center",
    marginBottom: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  heroIconWrapper: {
    width: 72,
    height: 72,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  heroTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#1f2937",
    textAlign: "center",
    marginBottom: 8,
  },
  heroDesc: {
    fontSize: 14,
    color: "#6b7280",
    textAlign: "center",
    lineHeight: 22,
  },

  // Section
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#1f2937",
  },
  section: { marginBottom: 24 },

  // Contact grid
  contactGrid: { flexDirection: "row", gap: 10 },
  contactCard: {
    flex: 1,
    backgroundColor: COLORS.WHITE,
    borderRadius: 16,
    padding: 16,
    alignItems: "center",
    borderWidth: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
  },
  contactCardIconWrapper: {
    width: 48,
    height: 48,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  contactCardLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: "#6b7280",
    marginBottom: 4,
  },
  contactCardValue: {
    fontSize: 11,
    fontWeight: "700",
    color: "#1f2937",
    textAlign: "center",
  },

  // Action grid
  actionGrid: { flexDirection: "row", gap: 10 },
  actionButton: {
    flex: 1,
    backgroundColor: COLORS.WHITE,
    borderRadius: 16,
    padding: 16,
    alignItems: "center",
    borderWidth: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
  },
  actionIconWrapper: {
    width: 52,
    height: 52,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  actionTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: "#1f2937",
    marginBottom: 4,
    textAlign: "center",
  },
  actionDesc: {
    fontSize: 11,
    color: "#6b7280",
    textAlign: "center",
    lineHeight: 16,
  },

  // Info banner
  infoBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    backgroundColor: COLORS.WHITE,
    borderWidth: 2,
    borderColor: "#10b981",
    borderRadius: 16,
    padding: 16,
    marginBottom: 24,
  },
  infoBannerIcon: {
    width: 44,
    height: 44,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  infoBannerTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: "#1f2937",
    marginBottom: 4,
  },
  infoBannerText: { fontSize: 13, color: "#6b7280", lineHeight: 20 },
  infoBannerHighlight: { color: "#10b981", fontWeight: "700" },

  // FAQ
  faqCategoryHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: COLORS.WHITE,
    borderWidth: 2,
    borderColor: "#f3f4f6",
    borderRadius: 14,
    padding: 14,
    marginBottom: 8,
  },
  faqCategoryIcon: { fontSize: 22 },
  faqCategoryTitle: { fontSize: 15, fontWeight: "700", color: "#1f2937" },
  faqItem: {
    backgroundColor: COLORS.WHITE,
    borderWidth: 2,
    borderColor: "#f3f4f6",
    borderRadius: 12,
    marginBottom: 6,
    overflow: "hidden",
  },
  faqItemOpen: { borderColor: "#10b981" },
  faqQuestion: {
    flexDirection: "row",
    alignItems: "center",
    padding: 14,
    gap: 10,
  },
  faqArrow: { fontSize: 14, color: "#10b981", width: 16 },
  faqQuestionText: { flex: 1, fontSize: 14, fontWeight: "600", color: "#1f2937" },
  faqAnswer: {
    paddingHorizontal: 14,
    paddingBottom: 14,
    paddingLeft: 40,
    fontSize: 13,
    color: "#6b7280",
    lineHeight: 20,
  },
  faqSection: { marginBottom: 16 },

  // Modal
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.6)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  modalCard: {
    backgroundColor: COLORS.WHITE,
    borderRadius: 20,
    width: "100%",
    maxWidth: 480,
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: "#e5e7eb",
  },
  modalHeaderLeft: { flexDirection: "row", alignItems: "center", gap: 12 },
  modalIconWrapper: {
    width: 44,
    height: 44,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  modalTitle: { fontSize: 18, fontWeight: "700", color: "#1f2937" },
  modalCloseBtn: {
    width: 32,
    height: 32,
    backgroundColor: "#f3f4f6",
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  modalCloseText: { fontSize: 16, color: "#6b7280" },
  modalContent: { padding: 20 },
  modalInfoBox: {
    backgroundColor: "#f9fafb",
    borderRadius: 12,
    padding: 14,
    marginBottom: 16,
    gap: 6,
  },
  modalInfoRow: { flexDirection: "row", gap: 6 },
  modalInfoLabel: { fontSize: 13, fontWeight: "600", color: "#6b7280" },
  modalInfoValue: { fontSize: 13, fontWeight: "500", color: "#1f2937" },
  inputLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: "#374151",
    marginBottom: 6,
  },
  inputGroup: { marginBottom: 16 },
  textInput: {
    borderWidth: 2,
    borderColor: "#e5e7eb",
    borderRadius: 12,
    padding: 12,
    fontSize: 15,
    color: "#1f2937",
  },
  textInputFocused: { borderColor: "#10b981" },
  textArea: { height: 120, textAlignVertical: "top" },
  modalActions: {
    flexDirection: "row",
    gap: 12,
    padding: 20,
    borderTopWidth: 1,
    borderTopColor: "#e5e7eb",
  },
  cancelBtn: {
    flex: 1,
    padding: 14,
    borderWidth: 2,
    borderColor: "#e5e7eb",
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  cancelBtnText: { fontSize: 15, fontWeight: "600", color: "#6b7280" },
  submitBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    padding: 14,
    borderRadius: 12,
  },
  submitBtnText: { fontSize: 15, fontWeight: "700", color: COLORS.WHITE },
});
