export const NOTIFICATION_TYPES: Record<string, string> = {
  // ── SYSTEM ──────────────────────────────────────────
  SYSTEM_ANNOUNCEMENT: "SYSTEM_ANNOUNCEMENT",
  SYSTEM_MAINTENANCE: "SYSTEM_MAINTENANCE",

  // ── LANDLORD → HOUSE ────────────────────────────────
  LANDLORD_BROADCAST: "LANDLORD_BROADCAST",
  LANDLORD_INVOICE: "LANDLORD_INVOICE",
  LANDLORD_RULE_UPDATE: "LANDLORD_RULE_UPDATE",

  // ── INTERACTION ─────────────────────────────────────
  INTERACTION_COMMENT: "INTERACTION_COMMENT",
  INTERACTION_LIKE: "INTERACTION_LIKE",
  INTERACTION_MENTION: "INTERACTION_MENTION",

  // ── PAYMENT ─────────────────────────────────────────
  PAYMENT_DUE: "PAYMENT_DUE",
  PAYMENT_RECEIVED: "PAYMENT_RECEIVED",
};
