import { StyleSheet } from "react-native";

export const TenantHomeScreenStyle = StyleSheet.create({
  root: { flex: 1 },
  container: { flex: 1, backgroundColor: "#e8f1ef", paddingHorizontal: 18, paddingTop: 12 },
  center: { flex: 1, justifyContent: "center", alignItems: "center" },
  title: { fontSize: 30, fontWeight: "700", color: "#111827", marginBottom: 4 },
  subtitle: { fontSize: 15, color: "#4b5563", marginBottom: 16 },
  card: {
    backgroundColor: "#f5f5f5",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#e5e7eb",
    padding: 16,
    alignItems: "center",
  },
  roomCard: {
    backgroundColor: "#f5f5f5",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#dfe7e5",
    padding: 16,
  },
  roomCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  roomIconWrap: {
    width: 50,
    height: 50,
    borderRadius: 14,
    backgroundColor: "#c6f3e3",
    alignItems: "center",
    justifyContent: "center",
  },
  rentedBadge: {
    backgroundColor: "#c6f3e3",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  rentedBadgeText: {
    color: "#0f9f74",
    fontWeight: "700",
    fontSize: 13,
  },
  roomName: {
    color: "#111827",
    fontSize: 34,
    fontWeight: "700",
  },
  houseName: {
    marginTop: 2,
    marginBottom: 12,
    color: "#6b7280",
    fontSize: 16,
    fontWeight: "500",
  },
  roomInfoBox: {
    marginBottom: 10,
    borderRadius: 14,
    backgroundColor: "#eef0f1",
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
  },
  roomInfoTextWrap: {
    marginLeft: 10,
    flex: 1,
  },
  roomInfoLabel: {
    fontSize: 13,
    color: "#6b7280",
    marginBottom: 2,
  },
  roomInfoValue: {
    fontSize: 15,
    color: "#1f2937",
    fontWeight: "700",
  },
  landlordMessageButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#fff",
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  maintenanceCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f5f5f5",
    borderRadius: 24,
    padding: 20,
    marginTop: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  maintenanceIconContainer: {
    width: 56,
    height: 56,
    borderRadius: 16,
    backgroundColor: "#A855F7",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  maintenanceNotificationBadge: {
    position: "absolute",
    top: -4,
    right: -4,
    minWidth: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: "#EF4444",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 6,
    borderWidth: 2,
    borderColor: "#f5f5f5",
  },
  maintenanceNotificationText: {
    color: "#fff",
    fontSize: 11,
    fontWeight: "700",
  },
  maintenanceContent: {
    flex: 1,
    marginLeft: 16,
  },
  maintenanceTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#111827",
  },
  maintenanceDesc: {
    fontSize: 14,
    color: "#6b7280",
    marginTop: 4,
  },
  maintenanceArrow: {
    width: 24,
    height: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  maintenanceArrowText: {
    fontSize: 24,
    color: "#9ca3af",
  },
  alertCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f5f5f5",
    borderRadius: 16,
    padding: 16,
    marginTop: 16,
    borderLeftWidth: 4,
    borderLeftColor: "#3B82F6",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  alertIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: "#DBEAFE",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  alertContent: {
    flex: 1,
  },
  alertText: {
    fontSize: 14,
    color: "#111827",
    lineHeight: 20,
  },
  iconBox: {
    width: 66,
    height: 66,
    borderRadius: 20,
    backgroundColor: "#f5e6b0",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 12,
  },
  cardTitle: { fontSize: 20, fontWeight: "700", color: "#111827", marginBottom: 8 },
  info: { fontSize: 14, color: "#6b7280", textAlign: "center", marginBottom: 6 },
  joinBtn: {
    minWidth: "100%",
    height: 50,
    borderRadius: 12,
    backgroundColor: "#0ea58d",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginTop: 10,
  },
  joinText: { color: "#fff", fontWeight: "700", fontSize: 14 },
  backdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: "rgba(17,24,39,0.35)" },
  sheetKeyboardWrap: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: "flex-end",
  },
  sheet: {
    maxHeight: "86%",
    minHeight: 470,
    backgroundColor: "#fff",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  sheetHeader: {
    height: 64,
    borderBottomWidth: 1,
    borderBottomColor: "#e5e7eb",
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  sheetTitle: { fontSize: 18, fontWeight: "700", color: "#111827" },
  closeBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "#f3f4f6",
    alignItems: "center",
    justifyContent: "center",
  },
  tabs: { flexDirection: "row", borderBottomWidth: 1, borderBottomColor: "#e5e7eb" },
  tab: {
    flex: 1,
    height: 52,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    borderBottomWidth: 2,
    borderBottomColor: "transparent",
  },
  tabActive: { borderBottomColor: "#0ea58d" },
  tabText: { fontSize: 14, color: "#6b7280", fontWeight: "600" },
  tabTextActive: { color: "#0ea58d" },
  badge: {
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: "#ef4444",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 4,
    paddingHorizontal: 4,
  },
  badgeText: { color: "#fff", fontSize: 11, fontWeight: "700" },
  content: { padding: 16 },
  codeInput: {
    height: 48,
    borderWidth: 1,
    borderColor: "#d1d5db",
    borderRadius: 10,
    paddingHorizontal: 12,
    fontSize: 16,
    color: "#111827",
    marginBottom: 10,
  },
  codeText: {
    textAlign: "center",
    fontSize: 30,
    color: "#6b7280",
    fontWeight: "700",
    marginBottom: 12,
  },
  submitBtn: {
    height: 48,
    borderRadius: 12,
    backgroundColor: "#8a94a7",
    alignItems: "center",
    justifyContent: "center",
  },
  disabled: { opacity: 0.6 },
  submitText: { color: "#fff", fontWeight: "700" },
  inviteCard: {
    borderWidth: 1,
    borderColor: "#e5e7eb",
    borderRadius: 12,
    padding: 10,
    marginBottom: 10,
  },
  inviteTitle: { fontSize: 14, fontWeight: "700", color: "#111827", marginBottom: 4 },
  inviteInfo: { fontSize: 12, color: "#6b7280", marginBottom: 2 },
  acceptBtn: {
    marginTop: 8,
    height: 34,
    borderRadius: 10,
    backgroundColor: "#0ea58d",
    alignItems: "center",
    justifyContent: "center",
  },
  acceptText: { color: "#fff", fontSize: 12, fontWeight: "700" },
});
